In [1]:
import numpy as np

In [2]:
ar1 = np.array([25,56,12,85,34,75])
ar2 = np.array([42,3,86,32,856,46])

In [3]:
sp = list(ar1.shape)
print(sp)

[6]


In [4]:
#create a randon array of ar1 shape
rar1 = np.random.rand(sp[0])
print(rar1)

[0.92403185 0.77339607 0.96945024 0.12114556 0.75939662 0.54543031]


In [5]:
ar1 = ar1.astype('complex')
print(ar1)

[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


In [6]:
ar2 = ar2.astype('complex')
print(ar2)

[ 42.+0.j   3.+0.j  86.+0.j  32.+0.j 856.+0.j  46.+0.j]


In [7]:
ar1 = ar1.reshape(2,3)
ar2 = ar2.reshape(2,3)
print(ar1)
print(ar2)

[[25.+0.j 56.+0.j 12.+0.j]
 [85.+0.j 34.+0.j 75.+0.j]]
[[ 42.+0.j   3.+0.j  86.+0.j]
 [ 32.+0.j 856.+0.j  46.+0.j]]


In [8]:
ar3 = (ar1*ar1-ar2*ar2)/(ar1-ar2)
print(ar3)

[[ 67.-0.j  59.+0.j  98.-0.j]
 [117.+0.j 890.-0.j 121.+0.j]]


In [9]:
#a2-b2 = (a+b)(a-b)
ar4 = ar1+ar2
if ar3.all() == ar4.all() :
    print("True .. they are same")
else:
    print("False .. they are different")

True .. they are same


<h1>check on eye,zeros,ones</h1>

In [10]:
at1 = np.ones(10)
at2 = np.arange(10, dtype = np.float64)
at3 = at1 + at2
print(str(np.result_type(at1))+','+str(np.result_type(at3)))

float64,float64


In [11]:
at1 = np.arange(4)
at1.reshape(2,2)
print(at1.shape)
at1 = at1.reshape(2,2)
print(at1.shape)

(4,)
(2, 2)


In [12]:
at1 = np.arange(4)
at1 = at1.reshape(2,-1)
print(at1.shape)

(2, 2)


In [13]:
at1 = np.eye(10, dtype = int)
print(at1)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [14]:
at1 = np.zeros(10, dtype = int)
print(at1)

[0 0 0 0 0 0 0 0 0 0]


In [15]:
at1 = np.zeros((10,10), dtype = int)
print(at1)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


<h1>Cumulative Sum, Axis</h1>

In [16]:
S_X = np.array([[2,5,6,5],[4,8,6,5]])
S_Y = np.array([[6,7,5,9],[7,5,6,4]])
print(S_Y-S_X)

[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [17]:
print(S_X<2)
print(np.less(S_X,np.ones((2,4))*2))

[[False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]]


In [18]:
print(np.cumsum(S_X,axis=1)>=8)
print(np.cumsum(S_Y,axis=1)>=8)

[[False False  True  True]
 [False  True  True  True]]
[[False  True  True  True]
 [False  True  True  True]]


In [19]:
print(np.mean(S_X,axis=1)>=8)
print(np.mean(S_Y,axis=1)>=8)

[False False]
[False False]


In [20]:
print(np.mean(S_X,axis=0)>=8)
print(np.mean(S_Y,axis=0)>=8)

[False False False False]
[False False False False]


In [21]:
print(np.sum(S_X,axis=1))
print(np.sum(S_Y,axis=1))

[18 23]
[27 22]


<h1>Diagnal & numpy special</h1>

In [22]:
print(np.diag([4,5,6],k=1))

[[0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]
 [0 0 0 0]]


In [23]:
#negate if value between 6 and 10
arr = np.arange(11)
m = (arr>6)&(arr<10)
arr[m]*=-1
print(arr)

[ 0  1  2  3  4  5  6 -7 -8 -9 10]


<h1>Numpy Cheatsheet</h1>

<h1>1. On Dimensions </h1>

In [24]:
#1D array
arr = np.arange(10)
print(arr.ndim)
print(arr.shape)
print(len(arr))

1
(10,)
10


In [25]:
#2D array
arr = np.arange(10).reshape(2,5)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(len(arr[0]))

2
(2, 5)
2
5


In [26]:
#3D array
arr = np.arange(10).reshape(1,2,5)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(len(arr[0]))
print(len(arr[0][0]))

3
(1, 2, 5)
1
2
5


In [27]:
#Datatype casting explicitly
arr = arr.astype(np.str)
print(arr,type(arr))

[[['0' '1' '2' '3' '4']
  ['5' '6' '7' '8' '9']]] <class 'numpy.ndarray'>


<h1>2. initial Placeholders</h1>

In [28]:
#zeros
print(np.zeros((4,4)))
print(np.zeros((4,4),dtype=int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [29]:
#ones
print(np.ones((4,4)))
print(np.ones((4,4),dtype=str))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [30]:
#arange start,end,increment
print(np.arange(10,25,2))

[10 12 14 16 18 20 22 24]


In [31]:
#linspace start,end,no.of units
print(np.linspace(0,2,9))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [32]:
print(np.zeros((4,4),dtype=np.string_))

[[b'' b'' b'' b'']
 [b'' b'' b'' b'']
 [b'' b'' b'' b'']
 [b'' b'' b'' b'']]


In [33]:
# Eye or identity
print(np.eye(3))
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# Diagnol
print(np.diag([4,5,6],k=-2))
arr1 = np.diag([4,5,6],k=2)
arr2 = np.diag([2,3,4],k=-2)
arr3 = np.diag([1,2,3,4,5],k=0)
print(arr1+arr2+arr3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [4 0 0 0 0]
 [0 5 0 0 0]
 [0 0 6 0 0]]
[[1 0 4 0 0]
 [0 2 0 5 0]
 [2 0 3 0 6]
 [0 3 0 4 0]
 [0 0 4 0 5]]


In [35]:
#full dimensions,size
print(np.full((3,3),7))

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [36]:
#empty array
print(np.empty((3,2)))

[[-0.  0.]
 [-0.  0.]
 [-0.  0.]]


<h1>3. numpy Datatypes</h1>

In [37]:
np.int64 #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #Complex numbers represented by 128 floats
np.bool #Boolean type storing TRUE and FALSE values
np.object #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type

numpy.str_

In [38]:
arr = np.arange(10).reshape(1,2,5)
print(arr.dtype)
print(arr.dtype.name)
print(arr.size)

int32
int32
10


<h1>Help</h1>

In [39]:
print(np.info(np.ndarray.dtype))

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
None


<h1>4. Arithmetic Operations</h1>

In [40]:
arr = np.full((3,3),7)
print(str(arr)+'\n'+str(arr-2))

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [41]:
#Subtraction
print(arr-2)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [42]:
#Addition
print(arr+2)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [43]:
#Multipication and division
print((arr+2)/((arr-2)*2))

[[0.9 0.9 0.9]
 [0.9 0.9 0.9]
 [0.9 0.9 0.9]]


In [44]:
#Multiplication
print((arr-2)*2)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [45]:
#Multiplication
print(np.multiply(arr,arr))
print(arr*arr)

[[49 49 49]
 [49 49 49]
 [49 49 49]]
[[49 49 49]
 [49 49 49]
 [49 49 49]]


In [46]:
#Arithematic Operations
print(np.sin(arr)) #sin
print(np.cos(arr)) #Cos
print(np.sqrt(arr)) #square root
print(np.exp(arr)) #exponential
print(np.log(arr)) #log

[[0.6569866 0.6569866 0.6569866]
 [0.6569866 0.6569866 0.6569866]
 [0.6569866 0.6569866 0.6569866]]
[[0.75390225 0.75390225 0.75390225]
 [0.75390225 0.75390225 0.75390225]
 [0.75390225 0.75390225 0.75390225]]
[[2.64575131 2.64575131 2.64575131]
 [2.64575131 2.64575131 2.64575131]
 [2.64575131 2.64575131 2.64575131]]
[[1096.63315843 1096.63315843 1096.63315843]
 [1096.63315843 1096.63315843 1096.63315843]
 [1096.63315843 1096.63315843 1096.63315843]]
[[1.94591015 1.94591015 1.94591015]
 [1.94591015 1.94591015 1.94591015]
 [1.94591015 1.94591015 1.94591015]]


In [47]:
#Dot Operation
arr2 = np.zeros((3,3))
print(arr.dot(arr))
print(arr2.dot(arr))

[[147 147 147]
 [147 147 147]
 [147 147 147]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<h1>5. Array Comparisions</h1>

In [48]:
arr1 = arr
print(arr1==arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [49]:
#Checking if arr1 & arr are equal
if np.array_equal(arr1,arr):
    print('Equal Arrays')
else:
    print('Non equal Arrays')

Equal Arrays


In [50]:
#Checking if arr1 & arr2 are equal
arr2 = np.zeros((3,3))
if arr2.all()==arr1.all():
    print('Equal Arrays')
else:
    print('Non equal Arrays')

Non equal Arrays


In [51]:
#Checking if arr1 has any lesser values than in arr2
if arr2.any()>arr1.any():
    print('Has greater values')
else:
    print('No Lesser values')

No Lesser values


In [52]:
#Comparing using all()
arr2 = np.ones((3,3))
arr2 = arr2.astype(np.int)
arr2 = arr2*10
print(arr2)
print(arr1)
if (arr2>arr1).all():
    print('Has greater values')
else:
    print('No Lesser values')

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
Has greater values


In [53]:
#Comparing using Any()
arr2 = np.zeros((3,3))
arr2 = arr2.astype(np.int)
arr2[1][1] = 10
print(arr2)
print(arr1)
if (arr2>arr1).any():
    print('Has greater values')
else:
    print('No Lesser values')

[[ 0  0  0]
 [ 0 10  0]
 [ 0  0  0]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
Has greater values


<h1>6. Aggregate Functions</h1>

In [54]:
a = np.arange(2,10,2)
print(a)

[2 4 6 8]


In [55]:
a.sum()

20

In [56]:
a.mean()

5.0

In [57]:
print(a.min())
print(a.max())

2
8


In [58]:
#Axis = 0 -> rows/yaxis, Axis = 1 -> column/xaxis, Axis = 3 -> zaxis -- check on google
print(a.cumsum(axis=0))

[ 2  6 12 20]


In [59]:
c = a.reshape(4,1,1)
print(a.cumsum(axis=0))

[ 2  6 12 20]


In [60]:
a.std()

2.23606797749979

<h1>Axis</h1>

In [61]:
a.sum(axis = 0)

20

In [62]:
b = np.full((3,3,3),5)
b.cumsum(axis=1)

array([[[ 5,  5,  5],
        [10, 10, 10],
        [15, 15, 15]],

       [[ 5,  5,  5],
        [10, 10, 10],
        [15, 15, 15]],

       [[ 5,  5,  5],
        [10, 10, 10],
        [15, 15, 15]]], dtype=int32)

In [63]:
b = np.full((3,3,3),5)
b.cumsum(axis=2)

array([[[ 5, 10, 15],
        [ 5, 10, 15],
        [ 5, 10, 15]],

       [[ 5, 10, 15],
        [ 5, 10, 15],
        [ 5, 10, 15]],

       [[ 5, 10, 15],
        [ 5, 10, 15],
        [ 5, 10, 15]]], dtype=int32)

In [64]:
b = np.full((3,3,3),5)
b.cumsum(axis=0)

array([[[ 5,  5,  5],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[15, 15, 15],
        [15, 15, 15],
        [15, 15, 15]]], dtype=int32)

In [65]:
b = np.full((3,3,3),5)
b.cumsum(axis=0)
b1 = b[:][:][0]
b2 = b[:][:][1]
b3 = b[:][:][2]
print(b1)
print(b2)
print(b3)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [66]:
b = np.full((3,3,3),5)
b = b.cumsum(axis=0)
b1 = b[:][:][0]
b2 = b[:][:][1]
b3 = b[:][:][2]
print(b1)
print(b2)
print(b3)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[15 15 15]
 [15 15 15]
 [15 15 15]]


In [67]:
print(np.concatenate([b1,b2,b3],axis=0))

[[ 5  5  5]
 [ 5  5  5]
 [ 5  5  5]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [15 15 15]
 [15 15 15]
 [15 15 15]]


In [68]:
print(np.concatenate([b1,b2,b3],axis=1))

[[ 5  5  5 10 10 10 15 15 15]
 [ 5  5  5 10 10 10 15 15 15]
 [ 5  5  5 10 10 10 15 15 15]]


In [69]:
b1 = b1.reshape(3,3,1)
#print(b1)
b2 = b2.reshape(3,3,1)
#print(b2)
b3 = b3.reshape(3,3,1)
#print(b3)
#print('\n\n')
print(np.concatenate([b1,b2,b3],axis=2))
tp = np.concatenate([b1,b2,b3],axis=2)
print(tp.transpose())

[[[ 5 10 15]
  [ 5 10 15]
  [ 5 10 15]]

 [[ 5 10 15]
  [ 5 10 15]
  [ 5 10 15]]

 [[ 5 10 15]
  [ 5 10 15]
  [ 5 10 15]]]
[[[ 5  5  5]
  [ 5  5  5]
  [ 5  5  5]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[15 15 15]
  [15 15 15]
  [15 15 15]]]


In [70]:
x = np.linspace(0,9,27).reshape(3,3,3)
print(x)

[[[0.         0.34615385 0.69230769]
  [1.03846154 1.38461538 1.73076923]
  [2.07692308 2.42307692 2.76923077]]

 [[3.11538462 3.46153846 3.80769231]
  [4.15384615 4.5        4.84615385]
  [5.19230769 5.53846154 5.88461538]]

 [[6.23076923 6.57692308 6.92307692]
  [7.26923077 7.61538462 7.96153846]
  [8.30769231 8.65384615 9.        ]]]


In [71]:
print(x[:][:][0])

[[0.         0.34615385 0.69230769]
 [1.03846154 1.38461538 1.73076923]
 [2.07692308 2.42307692 2.76923077]]


In [72]:
z = np.arange(1,10).reshape(3,3)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
print(z.sum(axis = 0))
print('\n')
print(z.sum(axis = 1))

[12 15 18]


[ 6 15 24]


In [74]:
z = np.arange(1,10).reshape(3,3,1)
print(z)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [75]:
print(z.sum(axis = 0))
print('\n')
print(z.sum(axis = 1))
print('\n')
print(z.sum(axis = 2))

[[12]
 [15]
 [18]]


[[ 6]
 [15]
 [24]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


<h1>tril_indices(), mask_indices(), diag_indices()</h1>

In [76]:
mat = np.array([[10,5,9],
                [2,20,6],
                [8,3,30]]).reshape(3,3)
 
#Max elements w.r.t axis = 1 i.e., row-wise max elements
max = np.amax(mat,axis = 1)

#Upper diagonal 5,9,6
upper = np.triu_indices(mat.shape[0],1)
#Diagonal 10,20,30
main = np.diag_indices(mat.shape[0]) 
#Lower diagonal 2,8,3
lower = np.tril_indices(mat.shape[0],-1)

diag=[upper,main,lower]

for x in range(3):
    mat[diag[x]]+=max[x]

print(mat)

[[30 15 19]
 [32 40 16]
 [38 33 50]]


In [77]:
#Arguments - n (n*n matrix), mask function, k
a = np.mask_indices(3, np.triu, 1)
print(a)

(array([0, 0, 1], dtype=int64), array([1, 2, 2], dtype=int64))


<h1>Complex Problem </h1>

In [78]:
arr = np.arange(9, dtype = "float").reshape(3,3)
ind1 = np.array([[1,2],[0,1]])
ind2 = np.array([[0,2],[1,2]])
print(arr[ind1, ind2].sum())

17.0


In [79]:
arr = np.arange(9, dtype = "float").reshape(3,3)

In [80]:
print(arr[[[0,0],[0,1]],[[0,2],[1,0]]])

[[0. 2.]
 [1. 3.]]


In [81]:
arr[0][2]

2.0

In [90]:
print(arr[[0,0],[1,1]])

[1. 1.]


In [85]:
print(arr[[[0,0],[0,1],[0,2]],[[1,0],[1,1],[1,2]]])

[[1. 0.]
 [1. 4.]
 [1. 8.]]


In [86]:
print(arr)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
